version: '2'
services:
  cassandra:
    image: cassandra:3.7
    restart: always
    volumes:
      - cassandra:/var/lib/cassandra

  redis:
    image: redis:3.2.1-alpine
    restart: always
  
  worker:
    build: worker/
    image: nepeat/nsfwapi-worker
    links:
      - cassandra
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: True
    env_file: .env
volumes:
  cassandra:
    driver: local